name: Github pull request labels

on:
  issue_comment:
    types: [created, edited]
  workflow_call:


jobs:
  skip-test-labeler:
    if: ${{ github.event.issue.pull_request }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Skip check_pruned_graph
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.event.comment.body, '/test skip check_pruned_graph') }}
      with:
        labels: tests/skips/check_pruned_graph
  trigger-pipeline:
    if: ${{ github.event.issue.pull_request }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Print labels
      run: echo "${{ github.event.issue.labels }}"
    - name: Trigger pipeline
      if: ${{ startsWith(github.event.comment.body, '/test trigger pipeline')  && contains( github.event.issue.labels.*.name, 'operator-hosted-pipeline/failed') }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: tests/trigger/pipeline